version: '3.9'

services:

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ./mongo-data:/data/db
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASS

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASS
      ME_CONFIG_MONGODB_URL: mongodb://$MONGO_USER:$MONGO_PASS@mongo:$MONGO_PORT/
    depends_on:
      - mongo

