name: Branches pipeline
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - edited
      - reopened
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
      - name: Build Docker Image
        working-directory: ./web-app
        run: docker build -t ${{ vars.FULL_IMAGE_NAME }}:${{ github.sha }} -t ${{ vars.FULL_IMAGE_NAME }}:${{ github.head_ref }} .
      - name: Push Docker Image
        run: docker push --all-tags ${{ vars.FULL_IMAGE_NAME }}
