name: Branches pipeline
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - edited
      - reopened
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
      - name: Build Docker Image
        working-directory: ./web-app
        run: docker build -t ${{ vars.FULL_IMAGE_NAME }}:${{ github.sha }} -t ${{ vars.FULL_IMAGE_NAME }}:${{ github.head_ref }} .
      - name: Push Docker Image
        run: docker push --all-tags ${{ vars.FULL_IMAGE_NAME }}
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Azure Container Instances
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
          name: dataops-mlops-staging
          image: ${{ vars.FULL_IMAGE_NAME }}:${{ github.head_ref }}
          dns-name-label: dataops-mlops-staging
          cpu: 1
          memory: 0.5
          location: 'west us'
          environment-variables: port=80 log_level=debug workers=1
