name: Main pipeline
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
  build-and-push:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
      - name: Build Docker Image
        working-directory: ./web-app
        run:  |
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"
          docker build -t ${{ vars.FULL_IMAGE_NAME_PRODUCTION }}:${{ github.sha }} -t ${{ vars.FULL_IMAGE_NAME_PRODUCTION }}:latest -t ${{ vars.FULL_IMAGE_NAME_PRODUCTION }}:$latest_tag .
      - name: Push Docker Image
        run: docker push --all-tags ${{ vars.FULL_IMAGE_NAME_PRODUCTION }}
