name: Main pipeline
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Python Semantic Release
        uses: relekang/python-semantic-release@master
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
  build-and-push:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME  }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}
      - name: Build Docker Image
        working-directory: ./web-app
        run:  |
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"
          docker build -t ${{ vars.FULL_IMAGE_NAME }}:${{ github.sha }} -t ${{ vars.FULL_IMAGE_NAME }}:latest -t ${{ vars.FULL_IMAGE_NAME }}:$latest_tag .
      - name: Push Docker Image
        run: docker push --all-tags ${{ vars.FULL_IMAGE_NAME }}
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Azure Container Instances
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
          name: dataops-mlops-production
          image: ${{ vars.FULL_IMAGE_NAME }}:${{ github.sha }}
          dns-name-label: dataops-mlops-production
          cpu: 1
          memory: 0.5
          location: 'west us'
          environment-variables: port=80 log_level=info workers=4
